name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - azureml-inference-server-http
      - mlflow==2.11.3
      - azureml-mlflow
      - azureml-ai-monitoring
      - scikit-learn==1.2.2
      - pandas
      - numpy

